version: "3.2"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.production
    command: nginx
    labels:
      - netguru.appname=calculator
      - netguru.stage=production
    hostname: netguru.calculator.production.web
    networks:
      - frontend

networks:
  frontend:
    external:
      name: frontend
