version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/welcome
    ports:
      - "3000:3000"
    depends_on:
      - db  
  redis: 
    image: redis
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
     - .:/welcome
    depends_on:
     - db
     - redis
    env_file:
     - .env
  crono:
    build: .
    command: bundle exec crono start
    volumes:
     - .:/welcome
    depends_on:
     - db
     - redis
    env_file:
     - .env  
