## specify node version
FROM quay.io/netguru/ng-node:8 as builder

## add code & build app
ADD . $APP_HOME
RUN yarn install
RUN yarn build

## Real app image
FROM nginx:alpine as app

ENV VIRTUAL_HOST hyundaifinance.ie
ENV VIRTUAL_PORT 3000
## Copy build/ folder to new image
COPY --from=builder /app/build /app/dist
COPY nginx-production.conf /etc/nginx/nginx.conf

EXPOSE 3000
